version: '3.8'

services:
  ng:
    build:
      context: ./alto-ng
      dockerfile: Dockerfile
    container_name: ng
    ports:
      - 4200:4200
    volumes:
      - ./alto-ng:/app/alto-ng
    tty: true

  api:
    build:
      context: ./alto-api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    volumes:
      - ./alto-api:/app/alto-api
    networks:
      - backend
    depends_on:
      - db
    tty: true

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/app/db
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
networks:
  backend: